<?php echo $this->doctype(); ?>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('thedailypressreview.com')->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink()->prependStylesheet($this->basePath() . '/static/bootstrap/css/bootstrap.min.css');
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/static/bootstrap/js/bootstrap.min.js')
                                      ->prependFile($this->basePath()  . '/static/jquery/jquery.min.js') ?>

    </head>
    <body>
        <h1>Admin de déploiement</h1>
        <div class="nav-collapse collapse">
                <?php
                echo $this->navigation('vpwdeploytool_navigation')->menu()->renderMenu(null, array(
                    'minDepth' => 1,
                    'maxDepth' => 1,
                    'ulClass' => 'nav'
                ));
                ?>
        </div>
        <?php
        echo $this->content;

        echo $this->inlineScript();
        ?>
    </body>
</html>